# RAG Application Configuration
# =============================
# This file contains all configurable parameters for the RAG system.
# CLI arguments will override values specified here.

# === Model Configuration ===
embedding_model: "nomic-embed-text:v1.5"
generation_model: "qwen3:8b"
question_expansion_model: "qwen3:8b"
cross_encoder_model: "cross-encoder/ms-marco-MiniLM-L6-v2"

# === Infrastructure ===
ollama_base_url: "http://localhost:11434"
ollama_timeout: 120
ollama_connection_timeout: 5
chroma_persist: "chroma_db"
data_filepath: "data/corpus.csv"

# === LLM Generation Parameters ===
temperature: 0.1
max_tokens: 5000
top_p: 0.9
top_k: 5

# === RAG & Retrieval ===
max_context_docs: 10
initial_context_size: 50
max_expanded_questions: 10
subquestion_max_documents: 200
subquestion_fusion_max_documents: 200

# === Clustering ===
kmeans_n_clusters: 6
hdbscan_min_cluster_size: 5
cluster_laplace_smoothing: 0.1
cluster_sample_size: 100

# === MMR (Diversity) ===
mmr_relevance_weight: 0.9
mmr_top_k: 50

# === Question Expansion ===
question_expansion_temperature: 0.5
question_expansion_max_tokens: 500
question_expansion_top_p: 0.9

# === Runtime Control ===
verbose: true

# Note: 'model' and 'list_models' are CLI-only parameters and cannot be set here
